version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./src:/src
      - ./public:/public
    environment:
      - NODE_ENV=development
    stdin_open: true #interactive mode
    tty: true 
